import type { ShapeDef } from '../shared/types';

/** Pixel-art billboard shapes. Rows are top-to-bottom; R/B/G/Y/P are colors, '.' is empty. */
export const SHAPES: ShapeDef[] = [
  {
    id: 'heart',
    name: 'Heart',
    rows: [
      '..RR...RR..',
      '.RRRR.RRRR.',
      'RRPRRRRRRRR',
      'RRPRRRRRRRR',
      '.RPRRRRRRR.',
      '..RRRRRRR..',
      '...RRRRR...',
      '....RRR....',
      '.....R.....',
    ],
  },
  {
    id: 'tree',
    name: 'Tree',
    rows: [
      '.....Y.....',
      '....GGG....',
      '...GGRGG...',
      '..GGGGGGG..',
      '...GGGGG...',
      '..GGGRGGG..',
      '.GGGGBGGGG.',
      '..GGGGGGG..',
      '.GGRGGGGRG.',
      'GGGGGGGGGGG',
      '....YYY....',
      '....YYY....',
    ],
  },
  {
    id: 'star',
    name: 'Star',
    rows: [
      '.....Y.....',
      '.....Y.....',
      '....YYY....',
      '....YYY....',
      'YYYYYYYYYYY',
      '.YYYYRYYYY.',
      '..YYYRYYY..',
      '...YYYYY...',
      '..YYY.YYY..',
      '.YYY...YYY.',
      'YY.......YY',
    ],
  },
  {
    id: 'mushroom',
    name: 'Mushroom',
    rows: [
      '...RRRRR...',
      '..RRRRRRR..',
      '.RRPRRRPRR.',
      'RRRRRRRRRRR',
      'RRPRRRRRPRR',
      '.RRRRRRRRR.',
      '...YYYYY...',
      '...YYYYY...',
      '..YYYYYYY..',
      '..YYYYYYY..',
    ],
  },
  {
    id: 'smiley',
    name: 'Smiley',
    rows: [
      '...YYYYY...',
      '..YYYYYYY..',
      '.YYYYYYYYY.',
      'YYYBYYYBYYY',
      'YYYBYYYBYYY',
      'YYYYYYYYYYY',
      'YRYYYYYYYRY',
      'YYRRRRRRRYY',
      '.YYYRRRYYY.',
      '..YYYYYYY..',
      '...YYYYY...',
    ],
  },
  {
    id: 'ghost',
    name: 'Ghost',
    rows: [
      '...PPPPP...',
      '..PPPPPPP..',
      '.PPPPPPPPP.',
      'PPBBPPPBBPP',
      'PPBBPPPBBPP',
      'PPPPPPPPPPP',
      'PPPPPPPPPPP',
      'PPPPGGGPPPP',
      'PPPPPPPPPPP',
      'PPPPPPPPPPP',
      'P.PP.PPP.PP',
    ],
  },
];

export const SHAPE_BY_ID = new Map(SHAPES.map((s) => [s.id, s]));
