import type { ShapeDef } from '../shared/types';

/** Pixel-art billboard shapes. Rows are top-to-bottom; R/B/G/Y/P are colors, '.' is empty. */
export const SHAPES: ShapeDef[] = [
  {
    id: 'heart',
    name: 'Heart',
    rows: [
      '..MM...RR..',
      '.MMMM.RRRR.',
      'MMMMMRRRRRR',
      'MMMMMRRRRRR',
      '.MMMMRRRRR.',
      '..MMMRRRR..',
      '...MMRRR...',
      '....MRR....',
      '.....R.....',
    ],
  },
  {
    id: 'tree',
    name: 'Tree',
    rows: [
      '.....Y.....',
      '....GGG....',
      '...GGOGG...',
      '..GGGGGGG..',
      '...GGCGG...',
      '..GGGBGGG..',
      '.GGGGOGGGG.',
      '..GGCGGBG..',
      '.GGMGGGGCG.',
      'GGGGGGGGGGG',
      '....YYY....',
      '....YYY....',
    ],
  },
  {
    id: 'star',
    name: 'Star',
    rows: [
      '.....O.....',
      '.....O.....',
      '....OOO....',
      '....YYY....',
      'OOOOYYYOOOO',
      '.OOOYYYOOO.',
      '..OOYYYOO..',
      '...OYYYO...',
      '..OOO.OOO..',
      '.OOO...OOO.',
      'OO.......OO',
    ],
  },
  {
    id: 'mushroom',
    name: 'Mushroom',
    rows: [
      '...BBBBB...',
      '..BBBBBBB..',
      '.BBMBBBMBB.',
      'BBBBBBBBBBB',
      'BBMBBBBBMBB',
      '.BBBBBBBBB.',
      '...YYYYY...',
      '...YYYYY...',
      '..YYYYYYY..',
      '..YYYYYYY..',
    ],
  },
  {
    id: 'smiley',
    name: 'Smiley',
    rows: [
      '...CCCCC...',
      '..CCCCCCC..',
      '.CCCCCCCCC.',
      'CCCBCCCBCCC',
      'CCCBCCCBCCC',
      'CCCCCCCCCCC',
      'CRCCCCCCCRC',
      'CCRRRRRRRCC',
      '.CCCRRRCCC.',
      '..CCCCCCC..',
      '...CCCCC...',
    ],
  },
  {
    id: 'ghost',
    name: 'Ghost',
    rows: [
      '...PPPPP...',
      '..PPPPPPP..',
      '.PPPPPPPPP.',
      'PPCCPPPCCPP',
      'PPCCPPPCCPP',
      'PPPPPPPPPPP',
      'PPPPPPPPPPP',
      'PPPPMMMPPPP',
      'PPPPPPPPPPP',
      'PPPPPPPPPPP',
      'P.PP.PPP.PP',
    ],
  },
];

export const SHAPE_BY_ID = new Map(SHAPES.map((s) => [s.id, s]));
